{{- if .Values.rbac.enabled }}
{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-controller-cluster-role
rules:
  - apiGroups: ["k8s.grafana.io"]
    resources: ["*"]
    verbs: ["*"]
---
{{ end -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-controller-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name | default "default" }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: grafana-controller-cluster-role
  apiGroup: rbac.authorization.k8s.io
{{ end -}}