{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "grafana-controller.serviceAccountName" . }}
  labels:
{{ include "grafana-controller.labels" . | nindent 4 }}
{{- end -}}
