
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - k8s.grafana.io
  resources:
  - dashboards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.grafana.io
  resources:
  - dashboards/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.grafana.io
  resources:
  - datasources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.grafana.io
  resources:
  - datasources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.grafana.io
  resources:
  - folders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.grafana.io
  resources:
  - folders/status
  verbs:
  - get
  - patch
  - update
