# Default values for grafana-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gmehta3/grafana-controller
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rbac:
  enabled: true
serviceAccount:
  create: true
  name: grafana-controller

args:
  grafana_endpoint: "http://access-grafana.cattle-prometheus.svc.cluster.local"
  grafana_token: "admin:password"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
